{% set name = "build-capi" %}
{% set version = "1.1.10" %}
{% set sha256 = "b4048fe3a1fa34e390eeae507c089499ab81cf9f34d8babfe229da20c0c2810a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - pytest-runner
  run:
    - python

test:
  requires:
    - pytest
  imports:
    - build_capi
  commands:
    - python -c "import build_capi"

about:
  home: https://github.com/limix/build-capi
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Build and distribute C/C++ static libraries'
  doc_url: https://github.com/limix/build-capi
  dev_url: https://github.com/limix/build-capi

extra:
  recipe-maintainers:
    - Horta
