travis:
  secure:
    BINSTAR_TOKEN: MiybTuYeO4ECHkdoa5PWYrn2BATW/3J6sruCeR64fNoJf2ZSMim428ewx66WqBfYIpw69rqBnmkfQJd+4VuZKYRC4Rmv9/JXolbIcDsua0IPdjFgTkMJbGvVvROS1rX+D4KJOwpcLtRGhLgDs445R9bau8LxsfJDeEXos2vP/1vFy1Z33yUofsp9BISGiRBKN82sn8SwfzPSl1bcdbEFnPhQFBC6GJT6+XS6jr7CfVsWAe6ue694OQtrvXJwSuCMy036ZTGVPVEGyBKaX8SwYuEb9H885tp0UaadteW1Ea3iI9y2ylufpwuzCK0GMKLhT0DwLeG/QuVmDqz7HjicaUR3X6aaRrE3Z6mMc16I8whS7LA9XLDG//Y6TqIoM1VMXvQptiQoCZfpGBJ45f0e79AXEAZCvTweQpuCo9ESMKtuJWtF1AFIAcQiJTb1Z8LTRJ59gjhnLYSLD7F/3Ypji3KXMZ/6OvnyewmC2ZNWUgpMiRzsfpKt6n2V+5okPY9Zxnnph9vrneni33i6E2453TpuSqB9yzsW7PJdYewkrCCY55Kuq8r2o7Q+75ofedwtHpCeyGcOqEotMfUd3Dl86X3KMF35xPGAaP19qYsr05zPNriSjdS5o/TF7oApUHW4plcr8OVf/THk3j/9AO+iZCCtvLl7Sz2et/yhbXO+QfI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
