travis:
  secure:
    BINSTAR_TOKEN: pT2CWN8udwZLhsPY7OlhRL9id6xc32MQWZxdQ8y45mqUSGaS7NYnat+Qmw6pHNss+Fg2GGc0ucFbLY/IQfJSBNOoiysqw96feJ7ld9SgPcJfCpUX0C4j2xHucwTPqJxR7DqSj53JjHkakWFeZLrKjCH3gikLlpO6J9cqRWt6DS9GTt4ZF+jBRHplBsfMJHvg1BD8QgNnK2puXM3r+byplJQNTKGzlLaVuYOu1ocviiR2PEO5mfuKyXiHDSr+GEyRi7fs8Fez7Bzj7/QvlVhT+2zCxHoEHT8NNxnrmm+yTj/GHb9eyEwk6N6KEFSyTOv2euKAn+4gl4PriKihtf10Sj9Mgj73bksNacQ2tqDCziZT8vR10CVRccZLfIjB74VYePQvUV9AO7cKvrKlYke21rG9xqWGQZ8PLybxyA0PJRkD7eIMEPEO/7ys0eHXqypG/OTJRQ5LQCWptpC+wvnBm31uVM90X2odn2VAH9bOtzBd4ll+3qn12QkiU+p0cFmOi85y0bCKMmONfQCThadF7Y1L7+jpANPFo/BoAEPblhqrSIx8PpyF6Lw3yRwUrHQSEH3XYJHcQz9bwV5vccFr6/i1aGi/1/ccsGSBcfCBNVqO+V2g+0pRTkw8bwhGMJAgM53laq1PYZb5NR65JSkuxyZj1NwIbEikmghcIUx8BuQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
